[package]
name = "message-actix"
version = "0.1.0"
authors = ["ty"]
edition = "2018"


[dependencies]
actix-web = "1.0"
env_logger = "0.6"
serde = { version = "1.0", features = ["derive"] }
serfe_json = "1.0"
